

;
; +-------------------------------------------------------------------------+
; |   This file	has been generated by The Interactive Disassembler (IDA)    |
; |	      Copyright	(c) 2011 Hex-Rays, <support@hex-rays.com>	    |
; |			 License info: 48-327F-7274-B7			    |
; |			       ESET spol. s r.o.			    |
; +-------------------------------------------------------------------------+
;
; Input	MD5   :	3567BAA62DFAC4848BC795A03B85E4B9
; Input	CRC32 :	42FCF02E

; ---------------------------------------------------------------------------
; File Name   :	C:\Users\RedskullDC\Downloads\omikron.bin
; Format      :	Binary file
; Base Address:	0000h Range: C000h - C800h Loaded length: 0800h

; Processor	  : z80	[]
; Target assembler: Zilog Macro	Assembler

; ===========================================================================

; Segment type:	Pure code
		segment	ROM
		org 0C000h

loc_C000:				; CODE XREF: ROM:C06Dj
		ld	a, 4
		jr	Init		; copy ourself to $4047H, $0047	after re-mapping
; ---------------------------------------------------------------------------
		jp	Read_KBD
; ---------------------------------------------------------------------------
		jp	ScreenOut
; ---------------------------------------------------------------------------
		jp	sub_C2E0
; ---------------------------------------------------------------------------
		jp	sub_C13B
; ---------------------------------------------------------------------------
		jp	sub_C160
; ---------------------------------------------------------------------------
		jp	loc_C3AA
; ---------------------------------------------------------------------------
		jp	DisplayString
; ---------------------------------------------------------------------------
		jp	loc_C44D
; ---------------------------------------------------------------------------
		jp	loc_C45F
; ---------------------------------------------------------------------------
		jp	sub_C414
; ---------------------------------------------------------------------------
		jr	CPM_Mode
; ---------------------------------------------------------------------------
		jp	loc_C480
; ---------------------------------------------------------------------------
		jp	loc_C5C2
; ---------------------------------------------------------------------------
		jp	loc_C5C8
; ---------------------------------------------------------------------------
		jp	loc_C541
; ---------------------------------------------------------------------------
		jp	loc_C571
; ---------------------------------------------------------------------------
		jp	sub_C472
; ---------------------------------------------------------------------------
		jp	0
; ---------------------------------------------------------------------------
		jp	0
; ---------------------------------------------------------------------------

Init:					; CODE XREF: ROM:C002j
		ld	hl, 47h	; 'G'   ; copy ourself to $4047H, $0047 after re-mapping
		ld	de, 4047h
		ld	bc, 5
		ldir
		out	(0), a		; Flip the memory config
		jp	loc_C04C	; Now executing	at $0049

loc_C04C:
		ld	sp, 200h
		call	Show_Menu

loc_C052:				; CODE XREF: ROM:C063j
		call	Read_KBD
		and	5Fh ; '_'
		cp	43h ; 'C'
		jr	z, CPM_Mode	; select CP/M Mode
		cp	54h ; 'T'
		jr	z, TRS80_Mode	; select TRS-80	Mode
		cp	50h ; 'P'
		jr	z, loc_C06F	; ??
		jr	loc_C052
; ---------------------------------------------------------------------------
		rst	38h
		ld	b, 0C0h	; '¿'

loc_C068:				; CODE XREF: ROM:C06Bj
		dec	bc
		ld	a, c
		or	b
		jr	nz, loc_C068
		jr	loc_C000
; ---------------------------------------------------------------------------

loc_C06F:				; CODE XREF: ROM:C061j
		scf

TRS80_Mode:				; CODE XREF: ROM:C05Dj
		ld	a, 8
		ld	hl, 0D3h ; '”'
		ld	(6Dh), hl
		jp	6Dh
; ---------------------------------------------------------------------------
; START	OF FUNCTION CHUNK FOR sub_C0C8

CPM_Mode:				; CODE XREF: ROM:C022j	ROM:C059j ...
		ld	sp, 100h
		ld	e, 1
		call	sub_C08C
		jr	loc_C0BB
; END OF FUNCTION CHUNK	FOR sub_C0C8

; =============== S U B	R O U T	I N E =======================================


sub_C085:				; CODE XREF: sub_C0C8-2Ap sub_C13B+2p	...
		ld	(bc), a
		ld	a, 4

Delay_A:				; CODE XREF: sub_C085+4j sub_C160+26p
		dec	a
		jr	nz, Delay_A
		ret
; End of function sub_C085


; =============== S U B	R O U T	I N E =======================================


sub_C08C:				; CODE XREF: sub_C0C8-48p sub_C414-3p
		call	sub_C094
		ld	b, 0C0h	; '¿'
		call	sub_C3A4
; End of function sub_C08C


; =============== S U B	R O U T	I N E =======================================


sub_C094:				; CODE XREF: sub_C08Cp	sub_C0C8-21p
		ld	a, e
		ld	(0F7E0h), a
		ld	bc, 0F7ECh
		ret
; End of function sub_C094

; ---------------------------------------------------------------------------
; START	OF FUNCTION CHUNK FOR sub_C0C8

loc_C09C:				; CODE XREF: sub_C0C8-2j
		ld	a, 3
		call	sub_C085

loc_C0A1:				; CODE XREF: sub_C0C8-25j
		ld	a, (bc)
		rrca
		jr	c, loc_C0A1
		ld	e, 1
		call	sub_C094
		ld	(0F7EEh), a
		ld	hl, 0
		call	sub_C13B
		jp	z, 0
		ld	a, (80h)
		bit	6, a

loc_C0BB:				; CODE XREF: sub_C0C8-45j
		ld	a, 0C0h	; '¿'
		jr	z, loc_C0C0
		rlca

loc_C0C0:				; CODE XREF: sub_C0C8-Bj
		ld	(80h), a
		ld	(0F7EEh), a
		jr	loc_C09C
; END OF FUNCTION CHUNK	FOR sub_C0C8

; =============== S U B	R O U T	I N E =======================================


sub_C0C8:				; CODE XREF: sub_C160+3Fp

; FUNCTION CHUNK AT C07B SIZE 0000000A BYTES
; FUNCTION CHUNK AT C09C SIZE 0000002C BYTES

		exx
		ld	hl, aProtected	; "\r\nPROTECTED\r\n"

loc_C0CC:				; CODE XREF: sub_C414-8p
		call	DisplayString
		ld	hl, aTypeC	; "TYPE C\r\n"
		call	DisplayString

loc_C0D5:				; CODE XREF: sub_C0C8+18j
		call	Read_KBD
		cp	3
		jr	z, CPM_Mode
		and	5Fh ; '_'
		cp	43h ; 'C'
		jr	nz, loc_C0D5
		exx
		ret
; End of function sub_C0C8

; ---------------------------------------------------------------------------
Menu:		.ascii '\r'             ; DATA XREF: Show_Menu+6o
		db  1Ch
aOmikronSystems:.ascii 'OMIKRON SYSTEMS   (C) 1981\r\n'
		.ascii 'MAPPER CP/M ADAPTOR    VER A.0\r\n'
		.ascii '\n'
		.ascii 'C = CP/M\r\n'
		.ascii '\n'
		.ascii 'T = TRS-80\r\n',0

; =============== S U B	R O U T	I N E =======================================


sub_C13B:				; CODE XREF: ROM:C00Dj	sub_C0C8-18p ...
		ld	a, 88h ; 'à'
		call	sub_C085
		ld	de, 0F7EFh

loc_C143:				; CODE XREF: sub_C13B+Bj
		ld	a, (bc)
		and	3
		jp	po, loc_C143

loc_C149:				; CODE XREF: sub_C13B+14j sub_C13B+19j
		ld	a, (de)
		ld	(hl), a
		inc	hl

loc_C14C:				; CODE XREF: sub_C13B+1Ej
		ld	a, (bc)
		and	2
		jr	nz, loc_C149
		ld	a, (bc)
		and	2
		jp	nz, loc_C149
		ld	a, (bc)
		rrca
		jp	c, loc_C14C
		ld	a, (bc)
		and	9Fh ; 'ü'
		ret
; End of function sub_C13B


; =============== S U B	R O U T	I N E =======================================


sub_C160:				; CODE XREF: ROM:C010j	ROM:C622p
		ex	af, af'
		ld	a, 0A8h	; '®'
		call	sub_C085
		ex	af, af'
		jr	nz, loc_C176

loc_C169:				; CODE XREF: sub_C160+Ej sub_C160+13j
		ld	a, (bc)
		rrca
		jr	nc, loc_C19B
		rrca
		jr	nc, loc_C169
		ld	a, (hl)
		ld	(de), a
		inc	hl
		jp	loc_C169
; ---------------------------------------------------------------------------

loc_C176:				; CODE XREF: sub_C160+7j sub_C160+19j
		ld	a, (bc)
		and	3
		jp	po, loc_C176
		ld	a, (hl)
		ld	(de), a
		ld	a, 0E0h	; '‡'
		ld	(0F7EEh), a
		inc	hl
		ld	a, 28h ; '('
		call	Delay_A
		ld	a, (bc)
		ld	a, (hl)
		ld	(de), a
		inc	hl
		ld	a, (bc)

loc_C18E:				; CODE XREF: sub_C160+34j
		ld	a, (hl)
		ld	(de), a
		inc	hl
		ld	a, (hl)
		ld	a, (bc)
		rrca
		jr	c, loc_C18E
		ld	a, 0C0h	; '¿'
		ld	(0F7EEh), a

loc_C19B:				; CODE XREF: sub_C160+Bj
		ld	a, (bc)
		ld	l, a
		and	40h ; '@'
		call	nz, sub_C0C8
		ld	a, l
		or	a
		ret
; End of function sub_C160


; =============== S U B	R O U T	I N E =======================================


ScreenOut:				; CODE XREF: ROM:C007j	Show_Menu+11p ...

; FUNCTION CHUNK AT C27A SIZE 00000023 BYTES

		ld	hl, (4Eh)
		bit	0, l
		jr	nz, loc_C1B5
		ld	a, h
		cp	7Fh ; ''
		jr	nz, loc_C1B5
		cp	c
		ret	z
		ld	c, 8

loc_C1B5:				; CODE XREF: ScreenOut+5j ScreenOut+Aj
		ld	hl, (40h)
		ld	a, h
		or	0FCh ; '¸'      ; screen starts at $FC00
		ld	h, a
		ld	a, (42h)
		ld	(hl), a
		ld	a, c
		ex	de, hl
		call	sub_C29D
		cp	20h ; ' '
		jr	c, loc_C221
		ld	hl, 0BFF9h
		bit	0, (hl)
		jr	nz, loc_C1DE
		cp	5Bh ; '['
		jr	nz, loc_C1D8
		ld	a, 5Eh ; '^'
		jr	loc_C1DE
; ---------------------------------------------------------------------------

loc_C1D8:				; CODE XREF: ScreenOut+2Dj
		cp	5Eh ; '^'
		jr	nz, loc_C1DE
		ld	a, 5Bh ; '['

loc_C1DE:				; CODE XREF: ScreenOut+29j
					; ScreenOut+31j ...
		ld	hl, 45h	; 'E'
		bit	3, (hl)
		jr	z, loc_C1E7
		and	7Fh ; ''

loc_C1E7:				; CODE XREF: ScreenOut+3Ej
		cp	0C0h ; '¿'
		jr	nc, loc_C20B

loc_C1EB:				; CODE XREF: ScreenOut+68j
		bit	0, (hl)
		jr	nz, loc_C1F9
		cp	80h ; 'Ä'
		jr	nc, loc_C1F9
		cp	60h ; '`'
		jr	c, loc_C1F9
		and	5Fh ; '_'

loc_C1F9:				; CODE XREF: ScreenOut+48j
					; ScreenOut+4Cj ...
		ex	de, hl
		call	char_to_screen

ShowCursor:				; DATA XREF: ScreenOut+7Do
		ld	a, h
		or	0FCh ; '¸'
		ld	h, a
		ld	a, (hl)
		ld	(42h), a
		ld	(hl), 5Fh ; '_' ; underscore char as the cursor
		ld	(40h), hl
		ret
; ---------------------------------------------------------------------------

loc_C20B:				; CODE XREF: ScreenOut+44j
		and	3Fh ; '?'
		jr	loc_C1EB
; ---------------------------------------------------------------------------

do_CursorHome:				; CODE XREF: ScreenOut+AFj
		ld	hl, 0FC00h
		xor	a
		out	(0FFh),	a
		jr	do_ClearEndOfField
; ---------------------------------------------------------------------------

do_move_cursor:				; CODE XREF: ScreenOut+88j
					; ScreenOut+8Fj
		add	hl, de
		ret
; ---------------------------------------------------------------------------

do_CursorLeft:				; CODE XREF: ScreenOut+9Fj
		dec	hl
		ret
; ---------------------------------------------------------------------------

do_CursorRight:				; CODE XREF: ScreenOut+A3j
		inc	hl
		ret
; ---------------------------------------------------------------------------

do_BackSpace:				; CODE XREF: ScreenOut+93j
		dec	hl
		ld	(hl), 20h ; ' ' ; destructive backspace
		ret
; ---------------------------------------------------------------------------

loc_C221:				; CODE XREF: ScreenOut+22j
		ex	de, hl
		ld	de, ShowCursor	; We return through ShowCursor
		push	de
		or	a
		ret	z
		cp	1Ah		; CursorDown, restore old char
		ld	de, 40h	; '@'   ; Add $40 (64) = 1 line
		jr	z, do_move_cursor
		cp	17h		; Cursor Up, restore old char
		ld	de, 0FFC0h	; Subtract $40 (64) = 1	line
		jr	z, do_move_cursor
		cp	8
		jr	z, do_BackSpace
		cp	0Ah
		jr	z, do_LineFeed
		cp	0Dh
		jr	z, do_Carriage
		cp	18h
		jr	z, do_CursorLeft
		cp	19h
		jr	z, do_CursorRight
		cp	1Fh
		jr	z, do_ClearEndOfField
		cp	1Eh
		jr	z, do_ClearEndOfLine
		cp	1Ch		; Home Cursor, clear screen
		jr	z, do_CursorHome
		cp	1Dh		; Home Cursor, don't clear screen
		ret	nz
		ld	hl, 0FC00h	; Resest Cursor	to start of screen mem
		ret
; End of function ScreenOut


; =============== S U B	R O U T	I N E =======================================


char_to_screen:				; CODE XREF: ScreenOut+55p
		ld	(hl), a
		inc	hl
		ld	a, h		; Check	for end	of Screen mem, if so fall through to Scroll
		or	a
		ret	nz
; End of function char_to_screen


; =============== S U B	R O U T	I N E =======================================

; start	of screen mem

do_ScrollScreen:			; CODE XREF: ScreenOut+F1p
		ld	de, 0FC00h
		ld	hl, 0FC40h	; Second Screen	Line
		ld	bc, 3C0h	; 15 lines worth of data (64 x 15)
		ldir
		ld	hl, 0FFC0h	; Position HL to start of last screen line

do_ClearEndOfField:			; CODE XREF: ScreenOut+70j
					; ScreenOut+A7j
		push	hl

loc_C271:				; CODE XREF: do_ScrollScreen+14j
		ld	(hl), 20h ; ' ' ; Clear last line
		inc	hl
		ld	a, l
		or	h
		jr	nz, loc_C271	; Clear	last line
		pop	hl
		ret
; End of function do_ScrollScreen

; ---------------------------------------------------------------------------
; START	OF FUNCTION CHUNK FOR ScreenOut

do_ClearEndOfLine:			; CODE XREF: ScreenOut+ABj
		push	hl
		ld	a, l
		and	3Fh ; '?'

loc_C27E:				; CODE XREF: ScreenOut+DFj
		ld	(hl), 20h ; ' '
		inc	hl
		inc	a
		cp	40h ; '@'
		jr	nz, loc_C27E
		pop	hl
		ret
; ---------------------------------------------------------------------------

do_Carriage:				; CODE XREF: ScreenOut+9Bj
		ld	a, l
		and	0C0h ; '¿'
		ld	l, a
		ret
; ---------------------------------------------------------------------------

do_LineFeed:				; CODE XREF: ScreenOut+97j
		push	hl
		ld	de, 40h	; '@'
		add	hl, de
		ld	a, h		; Are we past end of screen? HL	rolled to $0000
		or	a
		jr	nz, no_scroll
		call	do_ScrollScreen	; Move whole screen up a line
		pop	hl
		ret
; ---------------------------------------------------------------------------

no_scroll:				; CODE XREF: ScreenOut+EFj
		pop	de
		ret
; END OF FUNCTION CHUNK	FOR ScreenOut

; =============== S U B	R O U T	I N E =======================================


sub_C29D:				; CODE XREF: ScreenOut+1Dp
		ld	hl, 43h	; 'C'
		bit	0, (hl)
		jr	nz, loc_C2AD
		cp	1Bh
		ret	nz
		set	0, (hl)
		ret
; ---------------------------------------------------------------------------

loc_C2AA:				; CODE XREF: sub_C29D+18j sub_C29D+1Ej
		ld	a, b
		jr	loc_C2DD
; ---------------------------------------------------------------------------

loc_C2AD:				; CODE XREF: sub_C29D+5j
		bit	1, (hl)
		jr	nz, loc_C2C5
		ld	b, 1Ch
		cp	2Ah ; '*'
		jr	z, loc_C2AA
		ld	b, 1Eh
		cp	54h ; 'T'
		jr	z, loc_C2AA
		cp	3Dh ; '='
		jr	nz, loc_C2DD
		set	1, (hl)
		xor	a
		ret
; ---------------------------------------------------------------------------

loc_C2C5:				; CODE XREF: sub_C29D+12j
		sub	1Fh
		bit	2, (hl)
		jr	nz, loc_C2D9
		set	2, (hl)
		ld	de, 40h	; '@'
		ld	hl, 0FBC0h

loc_C2D3:				; CODE XREF: sub_C29D+38j
		add	hl, de
		dec	a
		jr	nz, loc_C2D3
		ex	de, hl
		ret
; ---------------------------------------------------------------------------

loc_C2D9:				; CODE XREF: sub_C29D+2Cj
		dec	a
		add	a, e
		ld	e, a
		xor	a

loc_C2DD:				; CODE XREF: sub_C29D+Ej sub_C29D+22j
		ld	(hl), 0
		ret
; End of function sub_C29D


; =============== S U B	R O U T	I N E =======================================


sub_C2E0:				; CODE XREF: ROM:C00Aj	Read_KBD+7p ...
		ld	hl, 4Eh	; 'N'
		ld	a, (0F87Fh)
		or	a
		jr	nz, loc_C2F3
		bit	2, (hl)
		ret	z
		res	2, (hl)
		call	sub_C3A2
		jr	loc_C2F5
; ---------------------------------------------------------------------------

loc_C2F3:				; CODE XREF: sub_C2E0+7j
		set	2, (hl)

loc_C2F5:				; CODE XREF: sub_C2E0+11j
		call	sub_C322
		or	a
		ld	(46h), a
		ret	z
		ld	a, 0FFh
		ret
; End of function sub_C2E0


; =============== S U B	R O U T	I N E =======================================


Read_KBD:				; CODE XREF: ROM:C004j	ROM:loc_C052p ...
		ld	hl, 46h	; 'F'
		ld	a, (hl)
		or	a
		jr	nz, loc_C30C
		call	sub_C2E0
		jr	Read_KBD
; ---------------------------------------------------------------------------

loc_C30C:				; CODE XREF: Read_KBD+5j
		ld	(hl), 0
		jp	p, loc_C31E	; Current Key stored at	$004F
		ld	hl, 45h	; 'E'
		bit	0, (hl)
		jr	z, Read_KBD
		ld	a, (hl)
		xor	2
		ld	(hl), a
		jr	Read_KBD
; ---------------------------------------------------------------------------

loc_C31E:				; CODE XREF: Read_KBD+Ej
		ld	(4Fh), a	; Current Key stored at	$004F
		ret
; End of function Read_KBD


; =============== S U B	R O U T	I N E =======================================


sub_C322:				; CODE XREF: sub_C2E0:loc_C2F5p
		ld	hl, 47h	; 'G'
		ld	bc, 0F801h
		ld	d, 0

loc_C32A:				; CODE XREF: sub_C322+13j
		ld	a, (bc)
		ld	e, a
		xor	(hl)
		ld	(hl), e
		and	e
		jr	nz, loc_C339
		inc	d
		inc	l
		rlc	c
		jp	p, loc_C32A
		ret
; ---------------------------------------------------------------------------

loc_C339:				; CODE XREF: sub_C322+Dj
		ld	e, a
		push	bc
		call	sub_C3A2
		pop	bc
		ld	a, (bc)
		and	e
		ret	z
		ld	a, d
		rlca
		rlca
		rlca
		ld	d, a
		ld	c, 1

loc_C349:				; CODE XREF: sub_C322+2Ej
		ld	a, c
		and	e
		jr	nz, loc_C352
		inc	d
		rlc	c
		jr	loc_C349
; ---------------------------------------------------------------------------

loc_C352:				; CODE XREF: sub_C322+29j
		ld	a, (0F880h)
		ld	b, a
		ld	a, d
		add	a, 60h ; '`'
		cp	8Ah ; 'ä'
		jr	nc, loc_C37F
		ld	hl, 0F840h
		cp	80h ; 'Ä'
		jr	c, loc_C36C
		bit	4, (hl)
		jr	z, loc_C37F
		sub	70h ; 'p'
		jr	loc_C399
; ---------------------------------------------------------------------------

loc_C36C:				; CODE XREF: sub_C322+40j
		bit	4, (hl)
		jr	nz, loc_C3A0
		ld	hl, 45h	; 'E'
		bit	1, (hl)
		jr	z, loc_C37B
		rrc	b
		jr	nc, loc_C39F

loc_C37B:				; CODE XREF: sub_C322+53j
		sub	20h ; ' '
		jr	loc_C39F
; ---------------------------------------------------------------------------

loc_C37F:				; CODE XREF: sub_C322+39j sub_C322+44j
		sub	90h ; 'ê'
		jr	nc, loc_C393
		add	a, 40h ; '@'
		cp	3Ch ; '<'
		jr	c, loc_C38B
		xor	10h

loc_C38B:				; CODE XREF: sub_C322+65j
		rrc	b
		jr	nc, loc_C39F
		xor	10h
		jr	loc_C39F
; ---------------------------------------------------------------------------

loc_C393:				; CODE XREF: sub_C322+5Fj
		rlca
		rrc	b
		jr	nc, loc_C399
		inc	a

loc_C399:				; CODE XREF: sub_C322+48j sub_C322+74j
		ld	hl, KeyTable
		add	a, l
		ld	l, a
		ld	a, (hl)

loc_C39F:				; CODE XREF: sub_C322+57j sub_C322+5Bj ...
		ld	d, a

loc_C3A0:				; CODE XREF: sub_C322+4Cj
		ld	a, d
		ret
; End of function sub_C322


; =============== S U B	R O U T	I N E =======================================


sub_C3A2:				; CODE XREF: sub_C2E0+Ep sub_C322+19p
		ld	b, 6
; End of function sub_C3A2


; =============== S U B	R O U T	I N E =======================================


sub_C3A4:				; CODE XREF: sub_C08C+5p sub_C3A4+3j
		dec	bc
		ld	a, b
		or	c
		jr	nz, sub_C3A4
		ret
; End of function sub_C3A4

; ---------------------------------------------------------------------------

loc_C3AA:				; CODE XREF: ROM:C013j	ROM:C3B1j
		ld	a, (0F7E8h)
		and	0F0h ; ''      ; $F7E8 = Line Printer port
		cp	30h ; '0'
		jr	nz, loc_C3AA
		ld	a, c
		ld	(0F7E8h), a
		cp	0Dh
		jr	z, loc_C3BE
		cp	0Ah
		ret	nz

loc_C3BE:				; CODE XREF: ROM:C3B9j
		dec	h
		ret

; =============== S U B	R O U T	I N E =======================================


Show_Menu:				; CODE XREF: ROM:C04Fp
		ld	hl, 0FFFFh
		ld	(4Eh), hl
		ld	hl, Menu	; "\r"

DisplayString:				; CODE XREF: ROM:C016j
					; sub_C0C8:loc_C0CCp ...
		xor	a
		ld	(43h), a	; save current character
		ld	c, (hl)
		or	c
		ret	z
		push	hl
		call	ScreenOut	; Output character (in A) to screen, HL	= current screen mem loc
		pop	hl
		inc	hl
		jr	DisplayString
; End of function Show_Menu

; ---------------------------------------------------------------------------
KeyTable:	db  0Dh			; DATA XREF: sub_C322:loc_C399o
		db  0Ah			; List of Control Chars
		db  13h
		db  5Eh	; ^
		db 8
		db  1Bh
		db  1Ah
		db  5Ch	; \
		db    0
		db    0
		db  7Fh	; 
		db  5Bh	; [
		db    9
		db  5Dh	; ]
		db  20h
		db  20h
		db  80h	; Ä
		db  5Fh	; _
		db  1Ch
		db  1Dh
		db  1Eh
		db  1Fh
		db  7Bh	; {
		db  7Ch	; |
		db  7Dh	; }
		db  7Eh	; ~
aProtected:	.ascii '\r\n'           ; DATA XREF: sub_C0C8+1o
		.ascii 'PROTECTED\r\n',0
aTypeC:		.ascii 'TYPE C\r\n',0   ; DATA XREF: sub_C0C8+7o
; ---------------------------------------------------------------------------
; START	OF FUNCTION CHUNK FOR sub_C414

DriveNotReady:				; CODE XREF: sub_C414+16j
		ld	hl, aNotReady	; "\r\nNOT READY\r\n"
		call	loc_C0CC
		ex	af, af'
		ld	e, a
		call	sub_C08C
; END OF FUNCTION CHUNK	FOR sub_C414

; =============== S U B	R O U T	I N E =======================================


sub_C414:				; CODE XREF: ROM:C01Fj	sub_C5A9+9p

; FUNCTION CHUNK AT C409 SIZE 0000000B BYTES

		ld	bc, 0F7ECh
		ex	af, af'         ; F7EC = Disk COmmand/Status register

loc_C418:				; CODE XREF: sub_C414+6j
		ld	a, (bc)
		rrca
		jr	c, loc_C418
		ld	a, 0D8h	; 'ÿ'
		call	sub_C085
		ld	a, (bc)
		and	2
		ld	d, a
		ld	h, 4Eh ; 'N'

loc_C427:				; CODE XREF: sub_C414+1Dj
		dec	hl
		ld	a, h
		or	l
		jr	z, DriveNotReady
		ld	a, (bc)
		and	2
		cp	d
		ld	d, a
		jr	z, loc_C427
		ret
; End of function sub_C414

; ---------------------------------------------------------------------------
aNotReady:	.ascii '\r\n'           ; DATA XREF: sub_C414:DriveNotReadyo
		.ascii 'NOT READY\r\n',0

; =============== S U B	R O U T	I N E =======================================


sub_C442:				; CODE XREF: ROM:C450p	ROM:C462p
		inc	hl
		ld	(hl), c
		inc	hl
		ld	(hl), b
		ld	l, 3Ah ; ':'
		ex	de, hl
		ld	bc, 7
		ret
; End of function sub_C442

; ---------------------------------------------------------------------------

loc_C44D:				; CODE XREF: ROM:C019j
		ld	bc, 0C78Bh
		call	sub_C442
		ld	hl, 0C458h
		jr	loc_C468
; ---------------------------------------------------------------------------
		db  12h
		db  1Fh
		db    3
		db    7
		db  47h	; G
		db 0C0h	; ¿
		db    3
; ---------------------------------------------------------------------------

loc_C45F:				; CODE XREF: ROM:C01Cj
		ld	c, 1Ah
		ld	b, h
		call	sub_C442
		ld	hl, 0C46Bh

loc_C468:				; CODE XREF: ROM:C456j
		ldir
		ret
; ---------------------------------------------------------------------------
		db  1Ah
		db  3Fh	; ?
		db    3
		db    7
		db 0F2h	; Ú
		db 0C0h	; ¿
		db    2

; =============== S U B	R O U T	I N E =======================================


sub_C472:				; CODE XREF: ROM:C033j	ROM:loc_C535p
		ld	a, (38h)
		or	a
		jp	nz, sub_C2E0
		ei
		nop
		di
		ld	a, (0BFE4h)
		ret
; End of function sub_C472

; ---------------------------------------------------------------------------

loc_C480:				; CODE XREF: ROM:C024j
		push	af
		ld	(0BFDAh), hl
		ld	hl, 0
		add	hl, sp
		ld	sp, 0BFDAh
		push	hl
		push	de
		push	bc
		ld	a, (0BFF0h)
		or	a
		jr	z, loc_C4CB
		ld	a, (0BFE8h)
		inc	a
		ld	hl, 0BFE9h
		cp	(hl)
		jr	nz, loc_C4C8
		ld	a, (42h)
		ld	c, a
		cp	20h ; ' '
		ld	b, 20h ; ' '
		jp	nz, loc_C4AD
		ld	a, (0BFEAh)
		ld	b, a

loc_C4AD:				; CODE XREF: ROM:C4A6j
		ld	a, (0BFE7h)
		xor	0FFh
		ld	(0BFE7h), a
		ld	hl, (40h)
		ld	a, 4
		ld	(0BFE9h), a
		ld	a, b
		jr	nz, loc_C4C6
		ld	a, 10h
		ld	(0BFE9h), a
		ld	a, c

loc_C4C6:				; CODE XREF: ROM:C4BEj
		ld	(hl), a
		xor	a

loc_C4C8:				; CODE XREF: ROM:C49Cj
		ld	(0BFE8h), a

loc_C4CB:				; CODE XREF: ROM:C492j
		call	sub_C2E0
		or	a
		jr	nz, loc_C50E
		ld	hl, 0BFEBh
		inc	(hl)
		ld	a, (0BFF8h)
		cp	(hl)
		jr	nz, loc_C529
		ld	a, (0BFF7h)
		ld	(hl), a
		ld	hl, (0BFECh)
		ld	a, (0BFEFh)
		cp	(hl)
		ld	a, (0BFEEh)
		jr	nz, loc_C529
		cp	13h
		jr	nz, loc_C511
		jr	loc_C529
; ---------------------------------------------------------------------------
		db  18h
		db  1Eh

; =============== S U B	R O U T	I N E =======================================


sub_C4F3:				; CODE XREF: ROM:loc_C50Ep ROM:C54Dj
		ld	hl, 47h	; 'G'

loc_C4F6:				; CODE XREF: sub_C4F3+8j
		ld	a, (hl)
		or	a
		jr	nz, loc_C4FD
		inc	hl
		jr	loc_C4F6
; ---------------------------------------------------------------------------

loc_C4FD:				; CODE XREF: sub_C4F3+5j
		ld	(0BFEFh), a
		ld	(0BFECh), hl
		xor	a
		ld	(0BFEBh), a
		call	Read_KBD
		ld	(0BFEEh), a
		ret
; End of function sub_C4F3

; ---------------------------------------------------------------------------

loc_C50E:				; CODE XREF: ROM:C4CFj
		call	sub_C4F3

loc_C511:				; CODE XREF: ROM:C4EDj
		ld	hl, (0BFE5h)
		ld	(hl), a
		inc	hl
		ld	a, 0FFh
		ld	(0BFE4h), a
		ld	a, l
		cp	0CAh ; ' '
		jr	nz, loc_C526
		ld	a, h
		cp	0BFh ; 'ø'
		jr	nz, loc_C526
		dec	hl

loc_C526:				; CODE XREF: ROM:C51Ej	ROM:C523j
		ld	(0BFE5h), hl

loc_C529:				; CODE XREF: ROM:C4D9j	ROM:C4E9j ...
		ld	a, (0F7E0h)
		pop	bc
		pop	de
		pop	hl
		ld	sp, hl
		ld	hl, (0BFDAh)
		pop	af
		ret
; ---------------------------------------------------------------------------

loc_C535:				; CODE XREF: ROM:C53Fj	ROM:C54Bj
		call	sub_C472
		or	a
		jr	nz, loc_C541
		call	sub_C2E0
		or	a
		jr	z, loc_C535

loc_C541:				; CODE XREF: ROM:C02Dj	ROM:C539j
		ld	a, (0BFE4h)
		or	a
		jr	nz, loc_C54F
		ld	a, (46h)
		or	a
		jr	z, loc_C535
		jr	sub_C4F3
; ---------------------------------------------------------------------------

loc_C54F:				; CODE XREF: ROM:C545j
		ld	hl, (0BFE5h)
		dec	hl
		ld	(0BFE5h), hl
		ld	a, l
		cp	0C0h ; '¿'
		jr	nz, loc_C564
		ld	a, h
		cp	0BFh ; 'ø'
		jr	nz, loc_C564
		xor	a
		ld	(0BFE4h), a

loc_C564:				; CODE XREF: ROM:C559j	ROM:C55Ej
		ld	a, (hl)

; =============== S U B	R O U T	I N E =======================================


sub_C565:				; CODE XREF: ROM:loc_C571p
		push	af
		ld	a, (38h)
		or	a
		jr	nz, loc_C56F
		ei
		nop
		di

loc_C56F:				; CODE XREF: sub_C565+5j
		pop	af
		ret
; End of function sub_C565

; ---------------------------------------------------------------------------

loc_C571:				; CODE XREF: ROM:C030j
		call	sub_C565
		call	ScreenOut
		ld	a, (42h)
		cp	20h ; ' '
		ld	a, 1
		jp	nz, loc_C583
		ld	a, 1Fh

loc_C583:				; CODE XREF: ROM:C57Ej
		ld	(0BFE9h), a
		xor	a
		ld	(0BFE8h), a
		ld	(0BFE7h), a
		ret

; =============== S U B	R O U T	I N E =======================================


sub_C58E:				; CODE XREF: ROM:C646p	sub_C66C+2p
		ld	(bc), a
		ld	a, 4

loc_C591:				; CODE XREF: sub_C58E+4j
		dec	a
		jr	nz, loc_C591

loc_C594:				; CODE XREF: sub_C58E+8j
		ld	a, (bc)
		rrca
		jr	c, loc_C594
		ret
; End of function sub_C58E


; =============== S U B	R O U T	I N E =======================================


sub_C599:				; CODE XREF: sub_C5A9+Cp ROM:C607p
		ld	a, 3
; End of function sub_C599


; =============== S U B	R O U T	I N E =======================================


sub_C59B:				; CODE XREF: ROM:loc_C5E1p
		exx
		ld	c, a

loc_C59D:				; CODE XREF: sub_C59B+Aj
		ld	d, 7

loc_C59F:				; CODE XREF: sub_C59B+7j
		dec	de
		ld	a, e
		or	d
		jr	nz, loc_C59F
		dec	c
		jr	nz, loc_C59D
		exx
		ret
; End of function sub_C59B


; =============== S U B	R O U T	I N E =======================================


sub_C5A9:				; CODE XREF: ROM:loc_C5D3p
					; ROM:loc_C5EBp
		ld	a, (0BFF2h)
		or	a
		jr	z, sub_C5BB
		call	sub_C5BB
		call	sub_C414
		call	sub_C599
		ld	(0BFF2h), a
; End of function sub_C5A9


; =============== S U B	R O U T	I N E =======================================


sub_C5BB:				; CODE XREF: sub_C5A9+4j sub_C5A9+6p ...
		ld	a, (0BFE3h)
		ld	(0F7E0h), a	; Model	1 - Interrupt port, Bit7 Clock,	Bit6 Disk
		ret
; End of function sub_C5BB

; ---------------------------------------------------------------------------

loc_C5C2:				; CODE XREF: ROM:C027j
		ld	iy, 0C618h
		jr	loc_C5CC
; ---------------------------------------------------------------------------

loc_C5C8:				; CODE XREF: ROM:C02Aj
		ld	iy, 0C61Dh

loc_C5CC:				; CODE XREF: ROM:C5C6j
		di
		ld	a, (0F7ECh)	; 1771 - Command/Status	register
		rlca
		jr	nc, loc_C5E4

loc_C5D3:				; CODE XREF: ROM:C627j
		call	sub_C5A9
		ld	a, (0BFDCh)
		and	40h ; '@'
		ld	a, 3
		jr	nz, loc_C5E1
		ld	a, 28h ; '('

loc_C5E1:				; CODE XREF: ROM:C5DDj
		call	sub_C59B

loc_C5E4:				; CODE XREF: ROM:C5D1j
		ld	hl, (1)
		ld	l, 34h ; '4'
		ld	(hl), 0

loc_C5EB:				; CODE XREF: ROM:C64Ej
		call	sub_C5A9
		ld	hl, (0BFE1h)
		ld	bc, 0F7ECh	; 1771 - Command/Status	register
		ld	de, 0F7EFh	; 1771 - Data Register
		ld	a, 0FFh
		cp	(hl)
		jr	z, loc_C640
		ld	a, (0BFF1h)
		cp	(hl)
		jr	z, loc_C60A
		ld	(de), a
		ld	(hl), a
		call	sub_C654
		call	sub_C599

loc_C60A:				; CODE XREF: ROM:C600j	ROM:C639j ...
		call	sub_C5BB
		ld	a, (0BFE0h)
		ld	(0F7EEh), a	; 1771 - Sector	Select register
		ld	hl, (0BFDEh)
		jp	(iy)
; ---------------------------------------------------------------------------
		call	sub_C13B
		jr	loc_C62A
; ---------------------------------------------------------------------------
		ld	a, (0BFDCh)
		bit	6, a
		call	sub_C160
		bit	6, a
		jr	nz, loc_C5D3
		or	a

loc_C62A:				; CODE XREF: ROM:C61Bj
		ret	z
		ex	af, af'
		ld	hl, (1)
		ld	l, 34h ; '4'
		inc	(hl)
		ld	a, (hl)
		cp	0Ah
		jr	z, loc_C650
		cp	5
		jr	c, loc_C60A
		ex	af, af'
		bit	4, a
		jr	z, loc_C60A

loc_C640:				; CODE XREF: ROM:C5FAj
		call	sub_C5BB
		ld	a, (0BFDDh)
		call	sub_C58E
		ld	hl, (0BFE1h)
		ld	(hl), 0
		jr	loc_C5EB
; ---------------------------------------------------------------------------

loc_C650:				; CODE XREF: ROM:C635j
		ld	a, 1
		or	a
		ret

; =============== S U B	R O U T	I N E =======================================


sub_C654:				; CODE XREF: ROM:C604p
		ld	a, (0BFDCh)
		bit	6, a
		ld	a, (0BFDDh)
		jr	nz, sub_C66C
		or	a
		jr	nz, sub_C66C
		ld	hl, 0F7EEh	; 1771 - Sector	Select register
		ld	(hl), 0C0h ; '¿'
		call	sub_C66C
		ld	(hl), 80h ; 'Ä'
		ret
; End of function sub_C654


; =============== S U B	R O U T	I N E =======================================


sub_C66C:				; CODE XREF: sub_C654+8j sub_C654+Bj ...
		or	10h
		call	sub_C58E
		ret
; End of function sub_C66C

; ---------------------------------------------------------------------------
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db  1Ah
		db    0
		db    3
		db    7
		db    0
		db 0F2h	; Ú
		db    0
		db  3Fh	; ?
		db    0
		db 0C0h	; ¿
		db    0
		db  10h
		db    0
		db    2
		db    0
		db    1
		db    7
		db  0Dh
		db  13h
		db  19h
		db    5
		db  0Bh
		db  11h
		db  17h
		db    3
		db    9
		db  0Fh
		db  15h
		db    2
		db    8
		db  0Eh
		db  14h
		db  1Ah
		db    6
		db  0Ch
		db  12h
		db  18h
		db    4
		db  0Ah
		db  10h
		db  16h
		db  12h
		db    0
		db    3
		db    7
		db    0
		db  47h	; G
		db    0
		db  3Fh	; ?
		db    0
		db 0C0h	; ¿
		db    0
		db  10h
		db    0
		db    3
		db    0
		db    1
		db    5
		db    9
		db  0Dh
		db  11h
		db    3
		db    7
		db  0Bh
		db  0Fh
		db    2
		db    6
		db  0Ah
		db  0Eh
		db  12h
		db    4
		db    8
		db  0Ch
		db  10h
		db  12h
		db    0
		db    3
		db    7
		db    0
		db  52h	; R
		db    0
		db  3Fh	; ?
		db    0
		db 0C0h	; ¿
		db    0
		db  10h
		db    0
		db    3
		db    0
		db  12h
		db    0
		db    3
		db    7
		db    0
		db 0A5h	; •
		db    0
		db  3Fh	; ?
		db    0
		db 0C0h	; ¿
		db    0
		db  10h
		db    0
		db    3
		db    0
		db  12h
		db    0
		db    3
		db    7
		db    0
		db 0ACh	; ¨
		db    0
		db  3Fh	; ?
		db    0
		db 0C0h	; ¿
		db    0
		db  10h
		db    0
		db    3
		db    0
aCopyright1981o:.ascii 'COPYRIGHT 1981OMIKRON SYSTEMSALL RIGHTS RESERVED\a'
		db  15h
aB:		.ascii 'Å'
		db 0FBh	; ˚
		db  41h	; A
		db 0FFh
; end of 'ROM'


		end
